### ISSUE TITLE
[Feature] Keyboard and Mouse Support

### ISSUE THREAD

**Issue by braxento** [redphx/better-xcloud#98]
- Device: M1 MacBook Pro 
- OS: MacOS
- Browser: Safari

Keyboard and Mouse support, pretty explanatory.

Not sure if this helps but: https://github.com/guilhermejfreitas/xcloud-with-keyboard-mouse

**Comment by redphx** [comment]
This feature takes a lot of time so I'm not sure whether I'll implement it or not. If I do, it will be created as a new script.

**Comment by Haisom** [comment]
@redphx could you explain what actually happened with your try to implement this feature on [Release 2.0](https://github.com/redphx/better-xcloud/releases/tag/v2.0)?

Also, could you update the 2.0 notes to make reference for this Issue? Thank you!

**Comment by redphx** [comment]
> @redphx could you explain what actually happened with your try to implement this feature on [Release 2.0](https://github.com/redphx/better-xcloud/releases/tag/v2.0)?
> 
> Also, could you update the 2.0 notes to make reference for this Issue? Thank you!

The MKB feature in 2.0 is not the same as this one.  

In version 2.0, I simply activated the MKB feature inside the xCloud website. But since xCloud disabled that feature it became non-functional. I won't try to activate it again as the devs don't want us to use.

**Comment by redphx** [comment]
I'm working on this feature. Follow this issue if you want to beta-test.

**Comment by hectorevil** [comment]
Thank you. i want to test too

**Comment by redphx** [comment]
### How to test
1. Install the [test version](https://github.com/redphx/better-xcloud/raw/feature/mouse_and_keyboard/better-xcloud.user.js) ([changelogs](https://github.com/redphx/better-xcloud/compare/main...feature/mouse_and_keyboard))
2. Settings > Enable Mouse & Keyboard support
3. Play any game

### How to use
Press F9 to toggle this feature.

Keys:
- Left stick: WASD
- Right stick: mouse movement
- Dpad: arrow keys
- A: Space, E
- B: Left Ctrl
- X: R
- Y: V
- LT: Right click
- RT: Left click
- Start: Enter
- Select: Tab
- LB: C, G
- RB: Q
- L3: Left Shift
- R3: F

### TODO
- [x] Enable native MKB support
- [x] Remapping
- [x] Profile/Preset
- [x] Adjust sensitivity
- [x] Hide cursor
- [x] Lock cursor to browser's window
- [ ] ~Import/Export~ (Save for later versions)

### Changelog

* **Jan 03**
  - Lock & hide the cursor. I tested and it felt much better than before.

* **Jan 01:**
  - The remapping feature is ready to be tested!.

* **Dec 29 2023:**
  - Implement new method to control analog stick using mouse. Heavily inspired by Yuzu's "Mouse panning" feature. Will add settings to control sensitivities later.
  - The key mapping feature is not working yet.
* **Dec 24 2023:**
  - Press **F9** to toggle MKB feature
  - Disable "Connect a controller" screen
  - Bug fixes
* [**Dec 23 2023:**](https://github.com/redphx/better-xcloud/issues/98#issuecomment-1868218122)
  - Enable native MKB support for some games. Only works in fullscreen mode.

* **Dec 21 2023:**
  - Add initial support

Feel free to suggest your ideas. Thanks.

<img width="480" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/01e6a72e-b1f8-4b82-87a1-543c313db5b5">

<img width="758" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/98d2a301-68b7-442a-a2d8-220877f02231">

**Comment by hectorevil** [comment]
Tested and works correctly both in cloud gaming and remote streaming. I have also tried to change the controls without any problems.


I know there are some games that support keyboard and mouse on the console natively like Halo Infinite which I have tested via remote reporduction but it detects the controller.
I guess it will be one of the limitations when "emulating" this feature.

**Comment by redphx** [comment]
@hectorevil thanks for testing.  

Yes, this is not the same as using native mouse & keyboard. Do you have any suggestions about this feature? I never try other m&kb extensions and I only play using controller so I don't know what to expect.

**Comment by hectorevil** [comment]
> @hectorevil thanks for testing.
> 
> Yes, this is not the same as using native mouse & keyboard. Do you have any suggestions about this feature? I never try other m&kb extensions and I only play using controller so I don't know what to expect.

For example on Xbplay allow to play using native mouse & keyboard on Remote and Xcloud. That's why I was asking



More features?
Tried another extensions/program like Xbplay or
 Keyboard & Mouse for Xbox xCloud which allo tow change Mouse Sensitivity or do presets for every game
![image](https://github.com/redphx/better-xcloud/assets/32722467/1bcb4565-343f-4550-a694-954f9cb5361d).

**Comment by redphx** [comment]
### Update Dec 27: xCloud disabled support for all other games, except Flight Simulator.

**Dec 23**
- Enable native MKB support for some games. ⚠️ Only works in fullscreen mode.   

```js
window.NATIVE_MKB_TITLES = [
    '9PMQDM08SNK9', // MS Flight Simulator

    // Not working anymore
    // '9NP1P1WFS0LB', // Halo Infinite
    // '9PJTHRNVH62H', // Grounded
    // '9P2N57MC619K', // Sea of Thieves
    // '9NBR2VXT87SJ', // Psychonauts 2
    // '9N5JRWWGMS1R', // ARK
    // '9P4KMR76PLLQ', // Gears 5
    // '9NN3HCKW5TPC', // Gears Tactics

    // Bugged
    // '9NG07QJNK38J', // Among Us
    // '9N2Z748SPMTM', // AoE 2
    // '9P731Z4BBCT3', // Atomic Heart
];
```

There could be more but I don't have time to test them all. Check [the full list](https://www.purexbox.com/guides/all-xbox-games-with-mouse-and-keyboard-support) of Xbox games that support MKB (some of these games might be bugged or not working).

@Haisom

**Comment by hectorevil** [comment]
tried a few games like Halo Infnite or Fortnite and works well.
Also tried High on Life but need some settings like mouse sensitivity

**Comment by redphx** [comment]
New UI changes:  
- Move stream stats & settings buttons to Stream HUD bar
- Split settings into tabs

<img width="800" src="https://github.com/redphx/better-xcloud/assets/96280/af66a4d1-cc6d-4f52-9b22-7255854290f1">

**Comment by ricardo404** [comment]
Is this testing feature still active? I tried here and even selecting the option to activate mouse and keyboard, nothing appears in the Better Xcloud menus, already inside the game (MSFS).

**Comment by AngusDLX** [comment]
I tested on MSFS and the simulator recognized the keyboard and mouse natively.

Incredible. The mouse just needs a few adjustments related to sensitivity and it will be perfect. You are on the right track.

The keyboard and mouse plugin for Xcloud made by David Idol/Modern Kit is a great interface reference.

I have good news too: The feature also accepts voice commands. Using Voice attack I was able to execute voice commands that activate the keys on the keyboard and mouse. For complex games this helps a lot!

**Comment by AngusDLX** [comment]
> Is this testing feature still active? I tried here and even selecting the option to activate mouse and keyboard, nothing appears in the Better Xcloud menus, already inside the game (MSFS).

I also had difficulty getting it to work. What I did was completely uninstall Better Xcloud from Tampermonkey, restart the browser, install the beta offered here and enable the keyboard and mouse function. After that I managed to make it work.

**Comment by ricardo404** [comment]
> > Esse recurso de teste ainda está ativo? Tentei aqui e mesmo selecionando a opção de ativar mouse e teclado, nada aparece nos menus Better Xcloud, já dentro do jogo (MSFS).
> 
> Também tive dificuldade para fazê-lo funcionar. O que eu fiz foi desinstalar completamente o Better Xcloud do Tampermonkey, reiniciar o navegador, instalar o beta oferecido aqui e ativar a função de teclado e mouse. Depois disso consegui fazer dar certo.

Hey Angus, I think I solved it, I forgot to read the part about (only works in full screen). This will solve our 737 double click problem, if you know what I mean. At least I tested it and it worked.

**Comment by AngusDLX** [comment]
> Hey Angus, I think I solved it, I forgot to read the part about (only works in full screen). This will solve our 737 double click problem, if you know what I mean. At least I tested it and it worked.

Yes it solves the problem. The hardest part now is using the keyboard and mouse to fly the aircraft. Are you using a control in conjunction with them? It's working fine?

I tried to configure the mouse to turn a "Yoke" and control the plane but the axes are only accepted up to the limit of the screen.

Even for future purposes, it is possible to use an unsupported peripheral such as (yokes, steering wheels, etc.) using an axis and button conversion software that would translate to the"virtual control". Unfortunately I lost all data about this. But it is possible.

**Comment by redphx** [comment]
**Dec 24:**
  - Press **F9** to toggle MKB feature
  - Disable "Connect a controller" screen
  - Bug fixes

**Comment by redphx** [comment]
WIP

<img width="475" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/5b8d76e0-85b3-4bcd-b6d8-95347f521560">

**Comment by LucasG021** [comment]
I tried to change the mouse sensitivity with JS, but nothing takes effect. Are you using any specific API for keyboard and mouse support?

**Comment by AngusDLX** [comment]
Using the latest version: I didn't find any bugs.

About compatibility with other controls:

*It was possible to use voice commands via voice attack to press the keys

*Virtual control was possible in conjunction with the keyboard and mouse in games that natively support K&M. I believe it works with a physical control too (I don't have one at the moment).

In the flight simulator I used the Vjoy + virtual controller to create a virtual XBOX control and transform the mouse inputs into the right stick inputs and thus control the plane. With a key configured to enable and disable the yoke, everything worked very well.

This possibility opens the door to configuring Joysticks and Steering Wheels in the future even if there is no official support from MS.

**Comment by LucasG021** [comment]
I just tested 65 games on xCloud, and all of them worked perfectly well with MKB compatibility. If you allow me, I can send you a list of the games I tested.

Regarding the mouse sensitivity, I haven't been able to solve it with JS yet. I could only manage it by using third-party programs to increase the DPI of my mouse.

**Comment by oDenial** [comment]
I tested Halo and loved the experience. Do you have plans to add a native keyboard and mouse to Fortnite?

**Comment by lnahuel16** [comment]
> I tested Halo and loved the experience. Do you have plans to add a native keyboard and mouse to Fortnite?

adds a new line of code: 'BT5P2X999VH2', // Fornite
below Gear Tactics, but as @LucasG021 mentions in the previous messages, it has a sensitivity bug, the only way to fix it for now is to increase the dpi of your mouse.

**Comment by oDenial** [comment]
Can you tell me in more detail, please? I don't know anything about it

**Comment by oDenial** [comment]
> > I tested Halo and loved the experience. Do you have plans to add a native keyboard and mouse to Fortnite?
> 
> adds a new line of code: 'BT5P2X999VH2', // Fornite below Gear Tactics, but as @LucasG021 mentions in the previous messages, it has a sensitivity bug, the only way to fix it for now is to increase the dpi of your mouse.

I did it, thanks

**Comment by redphx** [comment]
> I tested Halo and loved the experience. Do you have plans to add a native keyboard and mouse to Fortnite?

It's up to the game or xCloud, not me. All I did was enabling this feature.

**Comment by oDenial** [comment]
I did it, thanks

**Comment by oDenial** [comment]
> > Testei o Halo e adorei a experiência. Você tem planos para adicionar um teclado e mouse nativo ao Fortnite?
> 
> Cabe ao jogo ou ao xCloud, não a mim. Tudo o que fiz foi ativar esse recurso.

oh yes, thanks for that

**Comment by LucasG021** [comment]
The keyboard and mouse feature stopped working for me. Can you tell me if they disabled this feature?

**Comment by oDenial** [comment]
@redphx My native keyboard and mouse stopped working, do you know what could have happened?

**Comment by oDenial** [comment]
> The keyboard and mouse feature stopped working for me. Can you tell me if they disabled this feature?

mine too

**Comment by JUCIAN190** [comment]
my keyboard and mouse is not working in other games is only working in flight simulator

**Comment by TibiaCrft** [comment]
> my keyboard and mouse is not working in other games is only working in flight simulator

same.

**Comment by redphx** [comment]
It means xCloud disabled the native MKB feature on server-side for real this time.

**Comment by AngusDLX** [comment]
I can still use the Keyboard and Mouse. I decided to do a test flight on MSFS after receiving notifications here but in my case I can still use it lol

Maybe it will only be possible to use it in Flight Simulator and I hope it stays that way because it's 100% more fun to use the keyboard and mouse in this game (and also because I spent 2 days configuring the controls non-stop lol).

And an update on compatibility with other software: It is possible to use it with REWASD. With REWASD you can transform the mouse into a yoke and switch between the yoke and your normal mouse to press the buttons. It was the best solution I found related to virtualized controls.

This feature + voice attack to give voice commands is heaven

**Comment by oDenial** [comment]
> Isso significa que o xCloud desativou o recurso MKB nativo para real desta vez.

In other words, this was only available for a few days? now it will be impossible to use MKB with better xcloud

**Comment by Mobin735** [comment]
@redphx keyboard and mouse support didn't work for any reason, and when would it be fixed?

**Comment by oDenial** [comment]
> @redphx keyboard and mouse support didn't work for any reason, and when would it be fixed?

"It means xCloud disabled the native MKB feature on server-side for real this time."

**Comment by oDenial** [comment]
@redphx Do you know if you will be able to turn this feature back on?

**Comment by redphx** [comment]
@oDenial no

**Comment by oDenial** [comment]
> @oDenial no

This is so sad

**Comment by redphx** [comment]
* **Dec 29:**
  - Implement new method to control analog stick using mouse. Heavily inspired by Yuzu's "Mouse panning" feature. Will add settings to control sensitivities later.
  - The key mapping feature is not working yet.

**Comment by delicio002** [comment]
te amo

**Comment by oDenial** [comment]
> ### Update Dec 27: xCloud disabled support for all other games, except Flight Simulator.
> **Dec 23**
> 
> * Enable native MKB support for some games. ⚠️ Only works in fullscreen mode.
> 
> ```js
> window.NATIVE_MKB_TITLES = [
>     '9PMQDM08SNK9', // MS Flight Simulator
> 
>     // Not working anymore
>     // '9NP1P1WFS0LB', // Halo Infinite
>     // '9PJTHRNVH62H', // Grounded
>     // '9P2N57MC619K', // Sea of Thieves
>     // '9NBR2VXT87SJ', // Psychonauts 2
>     // '9N5JRWWGMS1R', // ARK
>     // '9P4KMR76PLLQ', // Gears 5
>     // '9NN3HCKW5TPC', // Gears Tactics
> 
>     // Bugged
>     // '9NG07QJNK38J', // Among Us
>     // '9N2Z748SPMTM', // AoE 2
>     // '9P731Z4BBCT3', // Atomic Heart
> ];
> ```
> 
> There could be more but I don't have time to test them all. Check [the full list](https://www.purexbox.com/guides/all-xbox-games-with-mouse-and-keyboard-support) of Xbox games that support MKB (some of these games might be bugged or not working).
> 
> @Haisom

Gears 5 also works with the native keyboard and mouse

**Comment by redphx** [comment]
Almost there...  
The remapping feature is not working yet, but you can play with MKB using the default mapping.

<img width="469" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/e55cbac6-c130-49f8-bec6-a54354f72693">

**Comment by delicio002** [comment]
Do you intend to add a feature to be able to control the games camera without the cursor appearing?, as if it were a native way?

**Comment by AngusDLX** [comment]
Microsoft Flight Simulator has stopped recognizing the keyboard and mouse natively.

R.I.P.

**Comment by AngusDLX** [comment]
> Do you intend to add a feature to be able to control the games camera without the cursor appearing?, as if it were a native way?

A good solution for this would be a key that inverts the mouse to control the left stick.

I did exactly that with REWASD. The mouse always controlled the right stick but if I pressed and held the alt key, the mouse controlled the left stick so I could move the camera. Designating a key to do this **inversion** would be a good idea.

It's very good for complex games like MSFS, No Man's Sky, car games, etc.

**Comment by delicio002** [comment]
quero muito que o dayz de certo com o teclado e mouse

**Comment by redphx** [comment]
> Do you intend to add a feature to be able to control the games camera without the cursor appearing?, as if it were a native way?

@AngusDLX @delicio002 there will be an option for that, but it will come later

**Comment by redphx** [comment]
The remapping feature is ready to be tested!  
I'll hide the cursor later.

<img width="480" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/b78d06c2-7a87-4f5b-873e-12900bcd075a">

**Comment by L4nzinhu** [comment]
**[Bug] Mouse having to move to the edges of the screen when you need to rotate the camera
Platform**

Device: Laptop
OS: Windows
Browser: Chrome
Browser Version:119
Better xCloud Version: 2.1.2

**Bug descrition:**
**It is only possible to rotate the camera a little, it is limited to the edges of the screen, this becomes even more problematic when taking the camera to look at the ground.**

Solution idea: lock the mouse in the center of the screen and make it invisible, but in a way that whenever we rotate the mouse it will not leave the center but the camera will be rotated.

VIDEO:

https://github.com/redphx/better-xcloud/assets/155100711/0464badd-0071-4467-8eae-78fa97fc1379

**Comment by redphx** [comment]
Added "Map mouse to" feature

<img width="435" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/879d2369-c141-4b5f-9ed8-3891a7d92801">

**Comment by redphx** [comment]
One question: does the mouse feel responsive?  
My laptop is really laggy + I have a high ping when using xCloud in general so it's really difficult for me to know how good/bad this feature is at the moment.

**Comment by delicio002** [comment]
> Uma pergunta: o mouse responde? Meu laptop está muito lento + tenho um ping alto ao usar o xCloud em geral, então é muito difícil para mim saber o quão bom/ruim esse recurso é no momento.

Yes, the mouse is responding normally, I tested it here and it's already better than last time, I haven't been able to test the mouse mapping yet.

**Comment by LucasG021** [comment]
I'm having trouble mapping the mouse; when I click on the input select, nothing appears

**Comment by redphx** [comment]
> I'm having trouble mapping the mouse; when I click on the input select, nothing appears

Which browser? Did you click on the "Edit" button?  
If possible please provide a video capture.

**Comment by LucasG021** [comment]
I tested it in two browsers, Google Chrome and Edge. I tried resetting the browser settings, but it didn't solve the issue. Here's a video: 

https://github.com/redphx/better-xcloud/assets/47404380/0b430dfe-a56b-44dc-a33a-a7c5836c2148

**Comment by redphx** [comment]
Try to create a new preset. The preset from the older version might be bugged.  

If it still doesn't work, please take a screenshot of the error in Console tab of [Chrome DevTools](https://developer.chrome.com/docs/devtools/open).  
You may need to clear the data in Chrome Devtools > Application > IndexedDB > xbox.com > right-click on "BetterXcloud" > Delete all > Reload the website

**Comment by LucasG021** [comment]
Now it works, thanks

**Comment by redphx** [comment]
@LucasG021 how was the experience?

**Comment by delicio002** [comment]
I couldn't, because I don't know how to use devtools

**Comment by redphx** [comment]
> I couldn't, because I don't know how to use devtools

Try again with the latest version

**Comment by Tak-attack** [comment]
The issue is different from MKB, but since the change to the new configuration UI, the pull downs and sliders do not move when clicked.
I have reinstalled better xcloud and deleted the cookie from xbox.com but it still does not work.

・Windows 10 
・Edge / Chrome

**Comment by redphx** [comment]
> The issue is different from MKB, but since the change to the new configuration UI, the pull downs and sliders do not move when clicked. I have reinstalled better xcloud and deleted the cookie from xbox.com but it still does not work.
> 
> ・Windows 10 ・Edge / Chrome

@Tak-attack in the stream settings?  
Do you see any error in the Console tab of [Chrome DevTools](https://developer.chrome.com/docs/devtools/open)?

**Comment by redphx** [comment]
<img width="758" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/20edcd7e-f65b-4e53-8081-61f6944ecefe">

Added feature to lock & hide the cursor. I tested and it felt much better than before.

All the features I wanted to added for the first version are done. If there are no more bugs I'll release the full version, so please help me test it.  

Thanks.

**Comment by LucasG021** [comment]
It's working perfectly for me, but I can't perform the action of holding the X button in Far Cry 6. I tested it on both Edge and Chrome browsers.

**Comment by LucasG021** [comment]
It's working perfectly for me. I tested it on the Edge and Chrome browsers. Thank you for your effort in providing such a useful extension. Soon, I'll be making a donation to express my gratitude for this.

**Comment by Tak-attack** [comment]
> > MKBとは問題が異なりますが、新しい設定UIに変更されてから、プルダウンやスライダーをクリックしても動かなくなりました。より良い xcloud を再インストールし、xbox.com から Cookie を削除しましたが、まだ機能しません。
> > ・Windows 10 ・エッジ / クローム
> 
> @Tak-attackストリーム設定で？[Chrome DevTools](https://developer.chrome.com/docs/devtools/open) の [コンソール] タブにエラーが表示されますか?[](https://developer.chrome.com/docs/devtools/open)

Yes, it is the Stream Settings pull-down.
But I just updated the script and checked again, and the Stream Settings pull-down menu and slider work as expected. Thanks for the fix!

**Comment by jonatanjrb** [comment]
It doesn't work for me at all, I've tried uninstalling and reinstalling it about 3 times, I've tried disconnecting my controller, and it doesn't work, it's a shame I wanted to do a mission in GTA that I could only do with a mouse in time

**Comment by redphx** [comment]
@jonatanjrb 
Browser? OS? Device? Screenshot? Video?  

Do you see any error in the Console tab of [Chrome DevTools](https://developer.chrome.com/docs/devtools/open)?

**Comment by redphx** [comment]
@jonatanjrb do you have the "Controller shortcuts" setting enable? Currently it conflict with the MKB feature, and I'll temporary disable it in the next version.

**Comment by redphx** [comment]
Version 3.0 with MKB support has been released. Thanks everyone for the help!

**Comment by delicio002** [comment]
Hello, could you explain to me what these functions (STICK DECAY STRENGTH) and (STICK DECAY MINIMUM) are for?

**Comment by redphx** [comment]
> Hello, could you explain to me what these functions (STICK DECAY STRENGTH) and (STICK DECAY MINIMUM) are for?

If you click on the (i) icon next to the big `Mouse & Keyboard` text it will take you to the docs: https://better-xcloud.github.io/mouse-and-keyboard/

**Comment by Sus002** [comment]
hello! first of all i wanted to thank you for doing this, its incredible, but now that the official release is out, i coudnt help to notice that the mouse being recognized internally by the mfs game and halo its not available anymore, for instance before on the beta i could move the mouse intwernally on the game, but now its just mapping the joystick, just wanted to ask if its a bug or you took it out, but even tho thanks for the great job on this exstention, fr.

**Comment by redphx** [comment]
@Sus002 the native mkb support feature can be disabled by xCloud anytime so I don't want to enable it by default.  

If you want to try it, change the `ENABLE_NATIVE_MKB_BETA` flag to `true`, and add the game you want to try to the `window.NATIVE_MKB_TITLES` list.

**Comment by Sus002** [comment]
> @Sus002 the native mkb support feature can be disabled by xCloud anytime so I don't want to enable it by default.
> 
> If you want to try it, change the `ENABLE_NATIVE_MKB_BETA` flag to `true`, and add the game you want to try to the `window.NATIVE_MKB_TITLES` list.

Ok thanks man!

**Comment by jonatanjrb** [comment]
no longer needed, thanks for your attention with stable update 3.0 with keyboard and mouse support it finally worked, I don't know what made it different for the final version that it didn't have in this test version but it worked, and it worked with the controller at the same time, it was very It's cool, I can use the mouse and the controller at the same time, the only thing is that you can't increase the speed of the pointer on the computer in GTA, for example, it turned everything up to maximum and it was still too slow, if you can do something to increase the speed? sensitivity to 300% or more would be great, for games like GTA that have a computer inside the game with a mouse pointer
________________________________
De: redphx ***@***.***>
Enviado: quinta-feira, 4 de janeiro de 2024 23:18
Para: redphx/better-xcloud ***@***.***>
Cc: jonatanjrb ***@***.***>; Mention ***@***.***>
Assunto: Re: [redphx/better-xcloud] [Feature] Keyboard and Mouse Support (Issue #98)


@Sus002<https://github.com/Sus002> the native mkb support feature can be disabled by xCloud anytime so I don't want to enable it by default.

If you want to try it, change the ENABLE_NATIVE_MKB_BETA flag to true, and add the game you want to try to the window.NATIVE_MKB_TITLES list.

**Comment by jonatanjrb** [comment]
I'm from Brazil and I'm using a  translator  controller and what do we call the joystick ok, so in my message when I say controller or control I'm referring to the xbox joystick in my case

**Comment by redphx** [comment]
@jonatanjrb for now you can edit the code to change the sensitivities: [Line 3759](https://github.com/redphx/better-xcloud/blob/main/better-xcloud.user.js#L3759) and [Line 3772](https://github.com/redphx/better-xcloud/blob/main/better-xcloud.user.js#L3772)

**Comment by delicio002** [comment]
Hi, could you tell me how I can modify the code on my computer, so that I can try the native feature?
